### ISSUE TITLE
plugin overrides loading parts

### ISSUE THREAD

**Issue by Valraven** [woothemes/theme-customisations#18]
As soon as I activate the plugin the loading parts in woocommerce don't work anymore. For example on the checkout page, API page (while adding a key). And I have no idea where else so far. The loading circle just keeps loading for ever, although the function behind it is doing its job (API key is added on refresh for example).

**Comment by jameskoster** [comment]
Hey, this is either another plugin or something you've added to this one yourself as on it's own this plugin doesn't actually _do_ anything. Could you share a URL? I might be able to diagnose the issue.

**Comment by Valraven** [comment]
Sure, I am currently working on a staging site so it doesn't interfere with the live site. http://sokkeposten.staging.wpengine.com/

**Comment by jameskoster** [comment]
Looks like javascript is failing to load on lots of your pages. I can't add products to the cart from your shop pages either.

I'm not seeing any errors but things like this are normally caused by incorrect asset loading order. IE perhaps a plugin is enqueuing jQuery manually and throwing things off.

I'd recommend disabling _all_ plugins until you find the culprit.

I'm going to close out this issue however as I am 99.9% certain that the theme-customisations plugin is not the culprit here.

**Comment by Valraven** [comment]
It was indeed my assumption as well, thanks for looking into it though. :)

**Comment by Valraven** [comment]
I have disabled all the plugins except woocommerce itself and the customizations plugin. Still the same problem.

**Comment by Valraven** [comment]
Alright. I found the culprit. And for those that might have the same problem at some point. Make sure that all your code is implemented through action hooks and functions. Especially custom tracking scripts. I fixed it by loading that tracking script through wp_print_footer_scripts by echo'ing it in a php function instead of the .js file.
